import { Guest } from "@/types";

export const guests: Guest[] = [
  {
    code: "GUEST001",
    idIssuedBy: "Cameroon",
    idExpiryDate: "2025-12-31",
    id: 1,
    name: "John M.",
    phone: "+237670123456",
    email: "john@example.com",
    nationality: "Cameroonian",
    idType: "National ID",
    idNumber: "CMR123456789",
    address: "Yaoundé",
    vehiclePlate: "CE 1234 AB",
    status: "Checked In",
  },
  {
    code: "GUEST002",
    idIssuedBy: "Cameroon",
    idExpiryDate: "2026-05-15",
    id: 2,
    name: "Grace N.",
    phone: "+237677654321",
    email: "grace@example.com",
    nationality: "Cameroonian",
    idType: "Passport",
    idNumber: "PA987654321",
    address: "Douala",
    status: "Reserved",
  },
  {
    code: "GUEST003",
    idIssuedBy: "Nigeria",
    idExpiryDate: "2024-11-20",
    id: 3,
    name: "Peter E.",
    phone: "+237699112233",
    email: "peter@example.com",
    nationality: "Nigerian",
    idType: "Passport",
    idNumber: "A12345678",
    status: "Checked Out",
  },
];