import { HotelRoom } from "@/types";

export const hotelRooms: HotelRoom[] = [
  {
    id: 1,
    number: "101",
    floor: 1,
    type: "Standard",
    price: 35000,
    capacity: 2,
    status: "Available",
    housekeepingStatus: "Clean",
    smoking: false,
    active: true,
  },
  {
    id: 2,
    number: "102",
    floor: 1,
    type: "Standard",
    price: 35000,
    capacity: 2,
    status: "Occupied",
    housekeepingStatus: "Clean",
    smoking: false,
    active: true,
  },
  {
    id: 3,
    number: "103",
    floor: 1,
    type: "Standard",
    price: 35000,
    capacity: 2,
    status: "Cleaning",
    housekeepingStatus: "In Progress",
    smoking: false,
    active: true,
  },
  {
    id: 4,
    number: "201",
    floor: 2,
    type: "Deluxe",
    price: 55000,
    capacity: 2,
    status: "Available",
    housekeepingStatus: "Clean",
    smoking: false,
    active: true,
  },
  {
    id: 5,
    number: "202",
    floor: 2,
    type: "Deluxe",
    price: 55000,
    capacity: 2,
    status: "Reserved",
    housekeepingStatus: "Clean",
    smoking: false,
    active: true,
  },
  {
    id: 6,
    number: "203",
    floor: 2,
    type: "Deluxe",
    price: 55000,
    capacity: 2,
    status: "Maintenance",
    housekeepingStatus: "Out of Service",
    smoking: false,
    active: false,
  },
  {
    id: 7,
    number: "301",
    floor: 3,
    type: "Executive Suite",
    price: 85000,
    capacity: 3,
    status: "Available",
    housekeepingStatus: "Clean",
    smoking: false,
    active: true,
  },
  {
    id: 8,
    number: "302",
    floor: 3,
    type: "Executive Suite",
    price: 85000,
    capacity: 3,
    status: "Dirty",
    housekeepingStatus: "Dirty",
    smoking: false,
    active: true,
  },
];